[.columns]
= Sentinel errors

[.column.is-half]
--
Global error variables

[source,go]
----
package fs

var ErrNotExist =
  errors.New("file does not exist")

var ErrExist =
  errors.New("file already exists")

var ErrPermission =
  errors.New("permission denied")
----
--

[.column.is-half]
--
* Prefix name with "Err"
* Avoid overly verbose names ([.step.small.strike]#ErrFileAlreadyExists#)
* Match with `errors.Is`
+
[%step]
[source,go]
----
if errors.Is(err, fs.ErrNotExist) {
  createFile(..)
}
----
--

[.notes]
--
Sentinel errors is just another way of saying
global error variables.
These are just top-level vars that you export from your package
so that users can match on them.

* Use these when your error message is fixed.
* Prefix the name of the top-level variable with "Err".
  This is a standard convention -- exceptions to it should be rare.
* Avoid overly verbose names for the error variables
  when you're using sentinel errors.
  Don't encode the entire message into the variable name.
  Don't call it "err file already exists" when "ErrExist" will suffice.

---

Once you set this up,
users will be able to match sentinel errors with the `errors.Is` function
in the standard library.
--
