[.columns.wrap]
= Keep interfaces small

[.column]
--
Bad

[source,go]
----
type Writer interface {
  WriteBytes([]byte) error
  WriteString(string) error
}

func (w *myWriter) WriteString(
  s string,
) error {
  return w.WriteBytes([]byte(s))
}
----
--

[.column,step=1]
--
Good

[source,go]
----
type Writer interface {
  WriteBytes([]byte) error
}

func WriteString(
  w Writer, s string,
) error {
  return w.WriteBytes([]byte(s))
}
----
--

[.column.is-full,step=1]
No helper methods -- use functions

[.notes]
--
Well, the first thing we do is preemptive.
Keep the interface small.

This ties into the thing I said earlier
about being deliberate about what you export.
Also be deliberate about what you add to an interface.

In this example, I have a Writer interface that defines two methods:
WriteBytes and WriteString.

Except that for the majority of cases,
WriteString is likely to be implemented like that --
by converting the string to a byte slice,
and calling WriteBytes.

Cases where it doesn't do that are going to be rare.
Yet, every implementation will have to have that same copy pasted snippet.

A solution here is to remove the method from the interface.
Move it to a top level function.

---

This makes the interface smaller,
and avoids the need to copy paste the implementation everywhere.

But this loses us the ability to customize WriteString
for the few cases where it doesn't have that implementation,
where it has a more optimized solution than this.

Is there a way to get that ability back?
There sure is!
--
