[.columns]
= Result Objects

[.column]
--
[source,diff]
----
 type DeleteUserResponse struct {
   Deleted bool
+  UUID    uuid.UUID
 }
----

[source,go]
----
func DeleteUser(
  ...
) (DeleteUserResponse, error) {
  // ...
}
----
--

[.column.text-left]
--
`struct` *exclusively* for returns except error

[.medium]
New fields for new outputs

[%step.small]
Need more than 2 results? +
Use a `struct`.
--

[.notes]
--
Result objects.
These are the other side of parameter objects.
Again, they're just another way of say a struct to hold the results.

The result object of a function exists similarly to hold the values returned by
it and is similarly exclusive.

Again, all results except the `error`.
If your function returns an error,
keep that outside the result object,
leave it as the last return value of your function.

Add new return values to your function if necessary,
by adding new fields to the struct.
This, too, is completely backwards compatible.

---

A similar rule of thumb applies here,
but with a different number.
If your function needs to return more than two things,
use a result object.
--
