= How to implement functional options

[.notes]
--
I skipped over the implementation side earlier
because it takes a little explanation.

There are a couple ways to implement functional options.
I'll go over the one I recommend.
--

[.columns%auto-animate]
= Setup

[.column.is-half]
[source%linenums,go,data-id=def]
----
type options struct {
}

type Option interface {
  apply(*options)
}
----

[.notes]
--
To implement functional options,

* Start with an *unexported* options struct.
  This struct will hold the final list of options.
* Define an *exported* `Option` interface,
  and to that add an *unexported* `apply` method
  that accepts a pointer to the `options` struct.

The unexported `apply` method "seals" the interface.
That means that nobody outside this package can implement this interface,
giving us full control of the list of implementations.

Now, define the option.
--

[.columns%auto-animate]
= Add an option

[.column]
[source%linenums,go,data-id=def]
----
type options struct {
  skipAuthors []string
}

type Option interface {
  apply(*options)
}
----

[.column]
[source,go]
----
func SkipAuthors(
  xs ...string,
) Option {
  return skipAuthors(xs)
}

type skipAuthors []string

func (o skipAuthors) apply(...) {
  opts.skipAuthors = []string(o)
}
----

[.notes]
--
To do that,

* Add a field to the unexported `options` struct
  that holds the data for your option.
* Add a top-level function named after the option
  that builds an implementation of the Option interface.
* In this implementation's `apply` method,
  set the newly added field in the `options` struct.

Do this for every other option.
--

[.columns%auto-animate]
= Add other options

[.column]
[source%linenums,go,data-id=def]
----
type options struct {
  skipAuthors []string
  archived    bool
  postedAfter time.Time
}

type Option interface {
  apply(*options)
}
----

[.column]
[source,go]
----
func SkipAuthors(
  xs ...string,
) Option { /* ... */ }

func Archived(
  archived bool,
) Option { /* ... */ }

func PostedAfter(
  postedAfter date.Date,
) Option { /* ... */ }
----

[.notes]
--
Lastly, consume the options.
--

[.columns%auto-animate]
= Consume the options

[.column.is-half]
[source%linenums,go,data-id=def]
----
type options struct {
  skipAuthors []string
  archived    bool
  postedAfter time.Time
}

type Option interface {
  apply(*options)
}
----

[.column]
[source,go]
----
func ListPosts(
  ctx context.Context,
  os ...Option,
) (...) {
  var opts options
  for _, o := range os {
    o.apply(&opts)
  }
  if opts.archived {
    // ...
  }
----

[.notes]
--
To do this, in your function,

* declare an instance of the unexported `options` struct
  with whatever default values you want to use.
  In this case, I'm just using the zero value.
* Then, for each provided instance of the `Option` interface,
  call the apply method on this `options` struct object.
* At the end of that loop, you have an options object ready to use.
  Inspect it and make your function do what it needs to do.

So this lets add any number of new optional parameters to our function.
What about return values?
Turns out, in a pinch,
you can use functional options to also produce new return values.
--

[.columns%auto-animate]
= Return new results

[.column]
[source%linenums,go,data-id=def]
----
type options struct {
  skipAuthors []string
  archived    bool
  postedAfter time.Time
  queryStats *Stats
}

type Stats struct {
  Elapsed time.Duration
  /* ... */
}

func QueryStats(*Stats) Option {
  /* ... */
}
----

[.column]
[source,go]
----
var stats Stats
posts, err := ListPosts(ctx,
  QueryStats(&stats),
)
if err != nil {
  // ...
}

log.Printf(
  "Query took %v", stats.Elapsed)
// Output:
// Query took 100ms
----

[.notes]
--
For that, declare a new option that accepts a pointer.
This pointer points to the variable that your function should fill
with that result.

For example, if my function optionally provided the ability to
calculate SQL query statistics,
I could add a `QueryStats` option which accepts a pointer to a `Stats`
variable.

A caller will provide a pointer to a variable from their local scope,
and be able to inspect it if your function returns successfully.

This is especially useful if your function has to do extra work
to calculate this new result.
You can make your function calculate it only if requested --
if the pointer is non-nil.
--
