= Driver Interface

[.notes]
--
Driver interface.

Okay, so I don't know the real name for this pattern.
I just made the name up. To be fair, all names are made up.

Let me explain the pattern at a high level first,
and then I'll demonstrate with code.
--

[%auto-animate]
== !

[mermaid,data-id=img]
....
flowchart LR
  subgraph "Driver interface"
    WriteBytes
  end
....

[.notes]
--
Under this pattern,
you start with a Driver interface with a small but powerful interface.

Powerful as in -- given that interface,
you can build most of the other functionality you need.
For example, if we were building an HTTP client,
the Driver interface would be a function
that takes a complex HTTP request object,
and returns a complex HTTP response object.

Around this interface, add a struct.
--

[%auto-animate]
== !

[mermaid,data-id=img]
....
flowchart LR
  subgraph "Writer struct"
    WriteBytesOut[WriteBytes]
  end

  subgraph "Driver interface"
    WriteBytes
  end

  WriteBytesOut --> WriteBytes
....

[.notes]
--
The struct begins with providing the same API as the driver,
mostly just proxying calls directly to it.

However, the key power here is that unlike interfaces,
you can add any number of new methods to a struct.

So you can add other functionality to this struct,
that you can implement in terms of the interface.
--

[%auto-animate]
== !

[mermaid,data-id=img]
....
flowchart LR
  subgraph "Writer struct"
    WriteBytesOut[WriteBytes]
    WriteString
  end

  subgraph "Driver interface"
    WriteBytes
  end

  WriteBytesOut & WriteString --> WriteBytes
....

[.notes]
--
This is very close to what we did with the top-level function earlier,
except users are expected to use the struct directly,
so they still get all methods on the same object.

Let me demonstrate with code quickly.
--

[%auto-animate%auto-animate-restart]
== !

[source,go]
----
type Driver interface {
  WriteBytes([]byte) error
}
----

[source%linenums,go,data-id=writer]
----
type Writer struct{ drv Driver }

func (w *Writer) WriteBytes(bs []byte) error {
  return w.drv.WriteBytes(bs)
}
----

[.notes]
--
I start with a Driver and a Writer.
The Driver implements the minimal, powerful interface.
The Writer holds a reference to a Driver,
and just forwards method calls over.
--

[%auto-animate]
== !

[source%linenums,go,data-id=writer]
----
type Writer struct{ drv Driver }

func (w *Writer) WriteBytes(bs []byte) error {
  return w.drv.WriteBytes(bs)
}

func (w *Writer) WriteString(bs []byte) error {
  return w.WriteBytes([]string(bs))
}
----

[.notes]
--
I add a new method to the Writer that relies on the existing functionality.
Because Writer is a struct, and not an interface,
adding this new method to it is completely backwards compatible.
--

[%auto-animate]
== !

[source,go]
----
type StringWriter interface {
  WriteString(string) error
}
----

[source%linenums,go,data-id=writer]
----
type Writer struct{ drv Driver }

func (w *Writer) WriteBytes(bs []byte) error {
  return w.drv.WriteBytes(bs)
}

func (w *Writer) WriteString(bs []byte) error {
  if sw, ok := w.drv.(StringWriter); ok {
    return sw.WriteString(s)
  }
  return w.WriteBytes([]string(bs))
}
----

[.notes]
--
I can add the same upcast-to-upgrade functionality to my driver
inside this new method.

So I sort of end up with the best of both worlds.
--

== Benefits

* Implement a small interface
* Consume a large surface
* Store internal state

[.notes]
--
Users that want to implement the interface
implement the smallest interface that satisfies their needs.
If the default behavior of WriteString is enough,
you don't have to implement it.
Just WriteBytes should suffice.

On the other side,
users that want to *consume* the abstraction still get the rich Writer struct
with its many convenience methods.
They don't have to constantly call into those pesky top level functions.

And lastly, because we now have this handy Writer struct sitting around,
we can store any amount of internal state into it.
--

== Examples

* `zap.Logger` wraps `zapcore.Core`
* `http.Client` wraps `http.RoundTripper`
* `database/sql` wraps `database/sql/driver`

[.notes]
--
This pattern is also used pretty widely.

* It's used inside Zap: the main Logger type actually wraps a Zap Core,
  which defines how to serialize a single Log entry.
  All convenience methods on the Logger -- Info, Warn, Error, etc.
  mostly just call into that function.
* Go's standard HTTP client wraps an HTTP RoundTripper.
  An HTTP RoundTripper takes a complex HTTP request object,
  and returns a complex HTTP response object.
  (I may have described it earlier without naming it.)
  All the convenience methods on http.Client -- Get, Post, etc.
  all mostly just build a Request object and call the RoundTripper.
* Lastly, database/sql -- nearly every type in that package wraps
  the smaller interfaces defined inside the database/sql/driver package.
--
