[%auto-animate]
= Upcast to upgrade

[.notes]
--
It's called upcasting!

With upcasting, we take a value implementing a certain interface,
and ask it *at runtime* whether it implements another interface as well.

Let me demonstrate.
--

[%auto-animate]
== !

[source%linenums,go,data-id=writer]
----
type Writer interface {
  WriteBytes([]byte) error
}

func WriteString(w Writer, s string) error {
  return w.WriteBytes([]byte(s))
}
----

[.notes]
--
So I have my Writer interface with its WriteBytes method,
and the WriteString function that converts the string to bytes,
and delegates to the Writer.

How do I add the ability for *some* of my Writer implementations to override
this behavior?

First, define a new interface.
--

[%auto-animate]
== Add a new interface

[source%linenums,go,data-id=writer]
----
type Writer interface {
  WriteBytes([]byte) error
}

type StringWriter interface {
  WriteString(string) error
}

func WriteString(w Writer, s string) error {
  return w.WriteBytes([]byte(s))
}
----

[.notes]
--
I define a new `StringWriter` interface here.
It has one method, WriteString, that matches the signature of my existing
top-level WriteString function -- minus the Writer argument.

This is the implement I want `Writer` implementations to also implement,
if they want to override the behavior of the WriteString function.
--

[%auto-animate]
== Upcast and use implementation

[source%linenums,go,data-id=writer]
----
type Writer interface {
  WriteBytes([]byte) error
}

type StringWriter interface {
  WriteString(string) error
}

func WriteString(w Writer, s string) error {
  if sw, ok := w.(StringWriter); ok {
    return sw.WriteString(s)
  }
  return w.WriteBytes([]byte(s))
}
----

[.notes]
--
Next, inside the WriteString function,
I attempt to *upcast* the Writer object into a StringWriter.
I ask it, *at runtime* whether it
implements the WriteString method defined by StringWriter.

If it does, I "upgrade" the code path.
I upgrade to the code path where I call the WriteString method
defined by the Writer.

If it does not implement that method, that is, that `ok` up there is false,
I fall back to the standard WriteString behavior --
convert the string to bytes and use WriteBytes.

This is a pretty simple technique used all over the place
to provide upgrade paths for interfaces.

As an example, let's look at the standard library's recently added io/fs
package.
--

[.columns.wrap%auto-animate]
== io/fs

[.column.is-half]
[source,go,data-id=fs]
----
type FS interface{
  Open(string) (File, error)
}
----

[.column.is-full%step]
[source%linenums,go,data-id=impl]
----
func Stat(fs FS, name string) (FileInfo, error) {
  f, err := fs.Open(name)
  if err != nil {
    return nil, err
  }
  return f.Stat()
}
----

[.notes]
--
io/fs defines a simple FS interface.
It defines the ability to open a file.
Nothing else.

---

Given that ability, I can implement a simple `Stat` function to inspect a file:
open the file and Stat it.

But what if my filesystem implementation is smarter,
and has the ability to stat a file without opening it?
For that, io/fs defines a StatFS interface and supports upgrading to it.
--

[.columns.wrap%auto-animate]
== io/fs

[.column.is-half]
[source,go,data-id=fs]
----
type FS interface{
  Open(string) (File, error)
}
----

[.column.is-half]
[source,go,data-id=upfs]
----
type StatFS interface {
  FS

  Stat(string) (FileInfo, error)
}
----

[.column.is-full]
[source%linenums,go,data-id=impl]
----
func Stat(fs FS, name string) (FileInfo, error) {
  if sf, ok := fs.(StatFS); ok {
    return sf.Stat(name)
  }

  f, err := fs.Open(name)
  if err != nil {
    return nil, err
  }
  return f.Stat()
}
----

[.notes]
--
If a file system implements the StatFS interface,
the `fs.Stat` function will use the Stat method defined by it.

io/fs does this for most of the filesystem-based functionality it privies.
For example, here's fs.ReadFile.
--

[.columns.wrap%auto-animate]
== io/fs

[.column.is-half]
[source,go,data-id=fs]
----
type FS interface{
  Open(string) (File, error)
}
----

[.column.is-half]
[source,go,data-id=upfs]
----
type ReadFileFS interface {
  FS

  ReadFile(string) ([]byte, error)
}
----

[.column.is-full]
[source%linenums,go,data-id=impl]
----
func ReadFile(fs FS, name string) ([]byte, error) {
  if rf, ok := fs.(ReadFileFS); ok {
    return rf.ReadFile(name)
  }

  f, err := fs.Open(name)
  if err != nil {
    return nil, err
  }
  return io.ReadAll(f)
}
----

[.notes]
--
If the filesystem provides a ReadFile method, use it.
Otherwise, open the file and read from it.

Note that the implementation for reading from a file is not quite that,
but it's what fits on this slide.
--

[.columns]
== Summary

[.column]
.Pros
* DRY implementation
* Upgrade as needed

[.column%step]
.Cons
* No internal state
* Wrapping breaks overrides

[.notes]
--
So, in summary, besides helping keeping your interface small,
this pattern

* Keeps your implementation DRY:
  you don't have to implement a method if you don't need to override its
  behavior. You have a guaranteed fallback behavior.
* You can add the ability to upcast to an interface *as needed*.
  You don't need to front load them.
  Add new upgrade paths as they become necessary.

But it's not all pros. There are some limitations.

* With this pattern, you do not have the ability to store any internal state
  from the helper function since you're operating strictly on interface values.
  There's no object for you to put private information inside.
** For example, as a convoluted use case,
   if my WriteString function earlier wanted to cache the byte slices it was
   generating, or keep count of the total number of bytes it had written,
   it would not be able to do that because it would have nowhere to store that
   information.
* The second, more significant limitation of this pattern is that if someone
  wraps my Writer implementation, but neglects to add the WriteString method
  which defines the upgrade path, then that optimization is lost.
  Any calls to the WriteString function with the wrapped Writer will use the
  fallback behavior because the wrapped Writer doesn't provide the WriteString
  method upgrade.

Overall, this pattern is still great.
Use it for small, simple interfaces that won't need too much state.

For other cases, there's another option.
--
