= Functional Options

[.notes]
--
Lastly there are functional options.
--

[.columns%auto-animate]
== !

[.column]
[source%linenums,go,data-id=decls]
----
type Option /* ... */

func SkipAuthors(
  names ...string,
) Option { /* ... */ }

func ListPosts(
  ctx context.Context,
  opts ...Option,
) ([]*Post, error)
----

[.column]
[source%linenums,go,data-id=usage]
----
ListPosts(ctx)

ListPosts(ctx,
  SkipAuthors(...),
)
----

[.notes]
--
With functional options, you define an opaque `Option` type.
I've omitted the implementation in this sample for now.

Since the `Option` type is opaque,
users cannot construct it directly.
Instead, you provide a fixed number of functions
that are able to construct this object.
In this example, it's `SkipAuthors`,
which itself takes some arguments
before it returns an Option value.

The function that these options are for
accepts a variable number of these
and interprets them "internally".
I'll elaborate on that in a minute.

But with this setup, users can pass this SkipAuthors option to ListPosts,
or they can omit it, depending on their needs.
--

[.columns%auto-animate]
== !

[.column]
[source%linenums,go,data-id=decls]
----
type Option /* ... */

func SkipAuthors(
  names ...string,
) Option { /* ... */ }

func Archived(
  bool,
) Option { /* ... */ }

func ListPosts(
  ctx context.Context,
  opts ...Option,
) ([]*Post, error)
----

[.column]
[source%linenums,go,data-id=usage]
----
ListPosts(ctx)

ListPosts(ctx,
  Archived(true),
  SkipAuthors(...),
)

ListPosts(ctx,
  Archived(false),
)
----

[.notes]
--
You can have any number of functions that build these option objects.
One for every different customizable option.

Users will pass only the ones they care about,
and everything else will use some default you control.
--

[.columns]
== !

[.column]
--
Do

* Zero argument default
* Required positional arguments
--


[.column]
--
Don't

* Required options
* Mix with parameter objects
--

[.notes]
--
With functional options,

* Use them for cases where you have a good zero argument default.
  That is, your function has a good, reasonable behavior
  without any options being provided.
* Do not add *required* options.
  You can see why from me saying "required option."
* If your function has any required parameters,
  those parameters should not become functional options.
  Keep them as regular positional parameters.
* Lastly, do not mix functional options with parameter objects in the same
  function.
  Use one or the other.
  Anything you wanted to make a functional option,
  turn it into an optional field of the struct.
--

include::pattern-func-opts-impl.adoc[leveloffset=+1]

== Summary

* Add new parameters or results
* Compose options together
+
[%step]
[source,go]
----
func(...Option) Option
----

High flexibility and high boilerplate

[.notes]
--
Okay, that was a lot about functional options.
In summary, functional options let you do a lot.

* add new parameters
* produce new results
* compose options together -- this is when you take a list of Options and
  return a new option

---

But functional options also come with a lot of boilerplate.
So use them only if the boilerplate is worth it.

---

As an aside,
I mentioned earlier that there are multiple ways to implement functional
options,
and that I'm demonstrating my preferred approach.

There's another approach based on function references that reduces the
boilerplate a little,
but I recommend you stick with the interface-based approach:

* the function reference version doesn't reduce the boilerplate *that* much
* but it loses some really good debugging and testing properties of the
  interface based approach

With the interface based approach,
you can actually make all your options printable, which aids in debugging,
as well as comparable, which helps in testing.
On top of that, the interface approach also provides you more flexibility --
options shared between functions, an upgrade path for the future,
and probably more that I can't recall yet.

So just in short:
if you're going to use functional options, use the interface based approach.
--
