[.columns.wrap.is-vcentered]
= Lifetime control

[.column.is-half.text-right]
All goroutines

[.column.is-half.text-left]
must finish or +
must be stoppable

[%step.column.is-full]
Do not fire-and-forget

[.notes]
--
Always control the lifetime of your goroutines.

All goroutines should,

* either have a known, predictable end time that you wait for
* or you must have the ability to tell them to stop

Do not fire and forget.
--

[.columns%auto-animate]
= !

[.column]
--
Bad

[source,go]
----
go func() {
  for {
    flush()
    time.Sleep(delay)
  }
}()
----

[.small,data-id=unstoppable]
Cannot be stopped
--

[%step.column]
--
[data-id=good-label]
Good

[source%linenums,go,data-id=good]
----
stop := make(chan struct{})
tick := time.NewTicker(delay)
go func() {
  for {
    select {
    case <-tick.C:
      flush()
    case <-stop:
      tick.Stop()
      return
    }
  }
}()
----

[.small,data-id=stoppable]
Can be stopped with +
`close(stop)`
--

[.notes]
--
As an example,
here's a simple worker goroutine
that periodically flushes some information.

It cannot be stopped.
This is bad.

A better way to accomplish this is with a combination of,

* a `stop` channel to tell your worker when to stop
* a `time.Ticker` to get the sleeps as a channel,
  with a means of stopping it

--

[.columns%auto-animate]
= !

[.column]
--
Bad

[source,go]
----
go func() {
  for {
    flush()
    time.Sleep(delay)
  }
}()
----

[.small,data-id=unstoppable]
Cannot be stopped
--

[.column]
--
[data-id=good-label]
Better

[source%linenums,go,data-id=good,highlight='|1,8,10']
----
ctx, cancel := /* ... */
tick := time.NewTicker(delay)
go func() {
  for {
    select {
    case <-tick.C:
      flush(ctx)
    case <-ctx.Done():
      tick.Stop()
      return
    }
  }
}()
----

[.small,data-id=stoppable]
Can be stopped with +
`cancel()`
--

[.notes]
--
An even better way of doing this is to use a context.
The context's done channel tells you when it's time to stop.

More importantly, you can pass that context down to
other operations you're running,
and so their lifetime will be likewise bounded.
--
